### ISSUE TITLE
No playlists showing when I import the merged file 

### ISSUE THREAD

**Issue by aslcouple** [pliniobrunelli/JWLSLMerge#1]
Hello. I tried to merge two backup files. One is about 200kb in size and the other 15kb. After running the command I get this error message:

"An error occurred while processing. Detail: The file 'C:\Users\Test\Downloads\JWLSLMerge-1.0\temp\manifest.json' already exists."

I've attached the 2 files I'm trying to merge.
[test files.zip](https://github.com/pliniobrunelli/JWLSLMerge/files/11244751/test.files.zip)

**Comment by CharllysFernandes** [comment]
I tried to make a python version as a personal project. If you want to test.

https://github.com/CharllysFernandes/JWLibraryMerger

**Comment by aslcouple** [comment]
Thank you for responding! I tried running it and it created the DB and Merged folders but no final .jwlibrary file. I am including my command prompt output, the DB and Merged folder contents, and the two playlists I was trying to merge (rename .zip files to .jwlibrary extension).

[CommandPromptOutput.txt](https://github.com/pliniobrunelli/JWLSLMerge/files/12156820/CommandPromptOutput.txt)
[Dir_DB.txt](https://github.com/pliniobrunelli/JWLSLMerge/files/12156821/Dir_DB.txt)
[Dir_Merged.txt](https://github.com/pliniobrunelli/JWLSLMerge/files/12156822/Dir_Merged.txt)
[test1.zip](https://github.com/pliniobrunelli/JWLSLMerge/files/12156823/test1.zip)
[test2.zip](https://github.com/pliniobrunelli/JWLSLMerge/files/12156824/test2.zip)

Let me know if you need anything else.

**Comment by pliniobrunelli** [comment]
Please download release 1.1 and try again. I had fixed the problem, but it took me a while to publish.


![test](https://github.com/pliniobrunelli/JWLSLMerge/assets/27024755/54cd386d-d62d-4c0b-a2c5-9c5a87705f49)

**Comment by aslcouple** [comment]
> Please download release 1.1 and try again. I had fixed the problem, but it took me a while to publish.
> 
> ![test](https://user-images.githubusercontent.com/27024755/255905672-54cd386d-d62d-4c0b-a2c5-9c5a87705f49.png)

Yes this works wonderfully! Thank you so much!

**Comment by pliniobrunelli** [comment]
>
