### ISSUE TITLE
Playlist are not merged with the new update

### ISSUE THREAD

**Issue by aslcouple** [pliniobrunelli/JWLSLMerge#3]
Sorry but the new 1.2 update doesn't work for me. Here are the playlists I am using. Rename these files and remove the .zip extension.

The merged file it creates is much smaller than either of the original 2 playlists.

[test1.jwlibrary.zip](https://github.com/pliniobrunelli/JWLSLMerge/files/12223940/test1.jwlibrary.zip)
[test2.jwlibrary.zip](https://github.com/pliniobrunelli/JWLSLMerge/files/12223941/test2.jwlibrary.zip)
[merged.jwlibrary.zip](https://github.com/pliniobrunelli/JWLSLMerge/files/12223942/merged.jwlibrary.zip)

**Comment by CharllysFernandes** [comment]
@aslcouple.
Try these files. Use parameters or no parameters for testing.

https://github.com/CharllysFernandes/JWLSLMerge/releases/tag/v.1.1.1

**Comment by aslcouple** [comment]
I tested JWLSLMerge.v1.1.1.for.Windows.compact.zip without parameters. Worked great! 

What is the Macs zip file? Will that run on a Mac computer?

**Comment by CharllysFernandes** [comment]
Yep!
